import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar/Navbar";
import { Toaster } from "@/components/ui/sonner"
import Mysessioncomponents from "./_components/Mysessioncomponents/Mysessioncomponents";
import CartContextprovider from "@/context/cartContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <Mysessioncomponents>
        
         <CartContextprovider>
             <Navbar/>
        {children}
         <Toaster />
         </CartContextprovider>

       </Mysessioncomponents>
      </body>
      
    </html>
  );
}
